# Deploy to Beget по SSH

name: Deploy to Beget

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '^19.8.0'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Beget
        env:
          SSH_KEY: ${{ secrets.BEGET_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H tfdf63.beget.tech >> ~/.ssh/known_hosts
          scp -r out/* tfdf63_tfdf@tfdf63.beget.tech:
